# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: discord-cleanup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: discord-cleanup

dockers_v2:
  - id: discord-cleanup
    image_templates:
      - "kwv4/discord-cleanup:{{ .Version }}"
      - "kwv4/discord-cleanup:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.version={{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - Dockerfile

archives:
  - formats: [tar.gz]
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
